version: "3.8"
services:
  mongo:
    command:
      - "--auth"
      - "-f"
      - "/etc/mongod.conf"
    volumes:
      - "$HOME/app_data/:/data/db"
      - "$HOME/configs/mongod.conf:/etc/mongod.conf"
    env_file:
      - "./modules/server/.env"
      - "./modules/server/.env.local"
  client:
    ports:
      - "80:8080"
