version: "3.8"
services:
  mongo:
    command:
      - "--auth"
      - "-f"
      - "/etc/mongod.conf"
    volumes:
      - "/hosted/db/poetro/data:/data/db"
      - "/hosted/db/poetro/mongod.conf:/etc/mongod.conf"
    env_file:
      - "./modules/server/.env"
      - "./modules/server/.env.local"
