version: "3.8"
services:
  mongo:
    image: "mongo:3.6"
    ports:
      - "27017:27017"
    networks:
      - poetronet
  server:
    build: ./src/server
    command: ["npm", "run", "start:dev"]
    ports:
      - "3000:3000"
    networks:
      - poetronet
    environment:
      - MONGODB_URI=mongodb://mongo/poetro
    volumes:
      - '/app/node_modules'
      - './src/server:/app'
    depends_on:
      - mongo
  client:
    build: ./src/client
    command: ["npm", "start"]
    volumes:
      - '/app/node_modules'
      - './src/client:/app'
    ports:
      - "8080:8080"
    environment:
      - HTTP_PROXY=http://server:3000
    networks:
      - poetronet
    depends_on:
      - server
networks:
  poetronet:
    driver: bridge
