version: "3.8"
services:
  mongo:
    command:
      - "--auth"
    volumes:
      - type: "bind"
        source: "/hosted/db/poetro/data"
        target: "/data/db"
    env_file:
      - "./modules/server/.env"
      - "./modules/server/.env.local"
