version: "3.8"
services:
  mongo:
    image: "mongo:3.6"
    ports:
      - "27017:27017"
    networks:
      - poetronet
  server:
    build:
      context: './modules/server'
    command: ["npm", "run", "start:dev"]
    ports:
      - "3000:3000"
    networks:
      - poetronet
    environment:
      - MONGODB_URI=mongodb://mongo/poetro
    depends_on:
      - mongo
  client:
    build:
      context: './modules/client'
    command: ["npm", "start"]
    ports:
      - "80:8080"
    environment:
      - HTTP_PROXY=http://server:3000
    networks:
      - poetronet
    depends_on:
      - server
networks:
  poetronet:
    driver: bridge
volumes:
  client_modules:
  server_modules:
