version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.6
      - image: circleci/mongo:3.6
    working_directory: ~/app
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - client-deps-{{ checksum "modules/client/package-lock.json" }}
            - client-deps-
            - server-deps-{{ checksum "modules/server/package-lock.json" }}

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npx lerna bootstrap
      - run: npm run test
