version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.6
      - image: circleci/mongo:3.6
    working_directory: ~/app
    steps:
      - checkout
      - run: npm install
      - run: npm run test
